### ISSUE TITLE
Getting error when app is building in release mode

### ISSUE THREAD

**Issue by Raviteja11122** [trevorwang/flutter-zxing#5]
This is my distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip
Gradle version classpath 'com.android.tools.build:gradle:3.4.1'

**Comment by trevorwang** [comment]
@Raviteja11122 Could you please provide the error logs?

**Comment by Raviteja11122** [comment]
@trevorwang 
This is error log
```
[        ] > Task :fzxing:extractReleaseAnnotations UP-TO-DATE
[        ] > Task :fzxing:mergeReleaseConsumerProguardFiles UP-TO-DATE
[        ] > Task :fzxing:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
[        ] > Task :fzxing:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
[        ] > Task :fzxing:transformNativeLibsWithSyncJniLibsForRelease UP-TO-DATE
[        ] > Task :fzxing:bundleReleaseAar UP-TO-DATE
[        ] > Task :fzxing:compileReleaseSources UP-TO-DATE
[  +91 ms] > Task :fzxing:mergeReleaseResources UP-TO-DATE
[  +74 ms] > Task :fzxing:verifyReleaseResources FAILED
[        ]          *********************************************************
[        ] WARNING: This version of connectivity will break your Android build if it or its dependencies aren't compatible with AndroidX.
[        ]          See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[        ]          This warning prints for all Android build failures. The real root cause of the error may be unrelated.
[        ]          *********************************************************
[        ] 446 actionable tasks: 7 executed, 439 up-to-date
[ +321 ms] Running Gradle task 'assembleRelease'... (completed in 6.0s)
[   +8 ms] "flutter run" took 9,664ms.
[        ] "flutter run" took 9,664ms.
Gradle task assembleRelease failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:462:5)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:331:14)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:43:10)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:378:13)
<asynchronous suspension>
#5      FlutterDevice.runCold (package:flutter_tools/src/resident_runner.dart:368:46)
<asynchronous suspension>
#6      ColdRunner.run (package:flutter_tools/src/run_cold.dart:61:39)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:405:37)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#15     Future._complete (dart:async/future_impl.dart:473:7)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#17     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#18     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#19     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#20     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#26     Future._complete (dart:async/future_impl.dart:473:7)
#27     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#28     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#29     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#30     AndroidDevice.targetPlatform (package:flutter_tools/src/android/android_device.dart)
#31     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#32     _rootRunUnary (dart:async/zone.dart:1132:38)
#33     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#34     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#35     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#36     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#37     Future._complete (dart:async/future_impl.dart:473:7)
#38     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#39     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#40     _rootRun (dart:async/zone.dart:1124:13)
#41     _CustomZone.run (dart:async/zone.dart:1021:19)
#42     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#43     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#44     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#45     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#46     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by trevorwang** [comment]
@Raviteja11122 Could you please provide the flutter version by `flutter doctor -v`

**Comment by trevorwang** [comment]
@Raviteja11122     
fixed this issue by following below instruction
https://stackoverflow.com/questions/24098494/error-when-generate-signed-apk

**Comment by Raviteja11122** [comment]
@trevorwang 
I'm still getting the same error. you created sample flutter project with kotlin support but in my case it is java 
that's why i'm getting this error

**Comment by trevorwang** [comment]
@Raviteja11122  Please add kotlin support by following instruction from https://developer.android.com/kotlin/add-kotlin
